/* eslint-disable */
// Originally generated by scripts/optimize-media.mjs.
//
// The `media/` source folder has since been deleted, so this can no longer be
// regenerated and is now maintained by hand. Restore the originals before
// running `npm run media` again — it would emit a manifest for whatever it
// finds, which is currently nothing.

export type MediaAsset = {
  readonly src: string;
  readonly width: number;
  readonly height: number;
  readonly blurDataURL: string;
};

export const IMAGES = {
  'butter-croissant': {
    src: '/media/butter-croissant.webp',
    width: 1254,
    height: 1254,
    blurDataURL:
      'data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADwAQCdASoOAA4AAwBSJagCdAEOQpabAUAA/vayWwObA/NA3R5FpQryHvAU2hgOXg0Yr7czzM/El5zEzFpjpxeX6TByf1ZyQK38oAygYbBbWsz71XkuppZY/tcwY/qo0BrPTVAA',
  },
  'cafe': {
    src: '/media/cafe.webp',
    width: 1402,
    height: 1122,
    blurDataURL:
      'data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAQCdASoOAAsAAwBSJagCdADw6p4FuCgA/ohs8p3EJd93BwOAjJ6uqJD0FKXkkT0Xk0uJNQLLZsOh5xKfVp4JvH1gOHvXFbCI+fX782UgkFYhSWnUZpNudsh2p9bYm/lt257JAAA=',
  },
  'cappuccino': {
    src: '/media/cappuccino.webp',
    width: 1254,
    height: 1254,
    blurDataURL:
      'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoOAA4AAwBSJagCdAELzdMtYMAAAP70XjuZyKsO8ScE+Z3eQU4Bg4h8QfVUFBxjV1MGGQrGZcEPYWv0m2sL76/zBqAAAA==',
  },
  'caramel-latte': {
    src: '/media/caramel-latte.webp',
    width: 1254,
    height: 1254,
    blurDataURL:
      'data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoOAA4AAwBSJbACdADWiBR4YNAA/vhpxgPifji9VexabpZnKvNw+rMFxXpDpBjm8E4JbbJg0hs6F/jkTElrF+z2x2ro6gwlhzbnqXF52gAAAA==',
  },
  'chocolate-muffin': {
    src: '/media/chocolate-muffin.webp',
    width: 1254,
    height: 1254,
    blurDataURL:
      'data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoOAA4AAwBSJQBOgCHdV23gCxeAAP72slaNbPfnYtoyg3I2dPTN77f5yxh1+GbaqR3bmBky7QPRjXlUaGusYrxhDq8SxvQVViMNGsE0zkAAAA==',
  },
  'classic-tiramisu': {
    src: '/media/classic-tiramisu.webp',
    width: 1254,
    height: 1254,
    blurDataURL:
      'data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAQCdASoOAA4AAwBSJagCdAEO9IvvNCAA/vW/21yx6rqsSoEXnOKcAHtxLwFdA7E4iMtYQX+iRlmqadI//6+CpcJrJTI+tTBnWOkq/oQmEnsDPX/YWhsFa+U80A7eQAA=',
  },
  'espresso': {
    src: '/media/espresso.webp',
    width: 1254,
    height: 1254,
    blurDataURL:
      'data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoOAA4AAwBSJZACdAELW86MamVoAP7515xBAHxg4AlkExfccgbF/XncX/7NavqXxDiNSSkz6mH51Ml8XG+8pv/XEWGDK0RiAAA=',
  },
  'grilled-chicken-sandwich': {
    src: '/media/grilled-chicken-sandwich.webp',
    width: 1402,
    height: 1122,
    blurDataURL:
      'data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQAgCdASoOAAsAAwBSJbACdAEN9c6DGadIAP7Zq1DYp7IRfz31yIw49b7jjBrMUWmxKJf7pQoDFMz2HJD7WhX8GmaIn3uveEF7nHArAVoZfBoZQg87yDY+B/t9u3rxpgo5rh0PrgAAAA==',
  },
  'iced-mocha-frappe': {
    src: '/media/iced-mocha-frappe.webp',
    width: 1122,
    height: 1402,
    blurDataURL:
      'data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABQAwCdASoOABEAPt1apkyopSOiMAgBEBuJQBOgA4SnouK2gAD+7C5vIOF/WJYb2S5J9J0n+4FFLU312Wj6z67nPzekOFOn0RG8adLcLmmRviF8HUJYyqEX1g/yN8H/9SaTin0KXvAAAA==',
  },
  'new-york-cheesecake': {
    src: '/media/new-york-cheesecake.webp',
    width: 1254,
    height: 1254,
    blurDataURL:
      'data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwAgCdASoOAA4AAwBSJZgCdAEO9cR5wXNXAAD++GjsowQLMKKesz9k3My1r4OSm0AsK/+6SOegPdipUsiui9niRd+rfjCDTf0gbU1Z2jWDgCfb8ZnynGgbKfQbjheagAA=',
  },
  'veg-club-sandwich': {
    src: '/media/veg-club-sandwich.webp',
    width: 1402,
    height: 1122,
    blurDataURL:
      'data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABQAgCdASoOAAsAAwBSJbACdAYv/WYQ4fwHeAAA/u+N5JF2PPuyOr7SvU+Z/Us2C8/vHWudxo48PGOzBZNvGkH/XZF2Fpd0h3qoVNzgNaeTXWw6e/qXEUs7hR0OX9rvJm1+1obhEqqsowJM5K0QAAAA',
  },
} as const satisfies Record<string, MediaAsset>;

export type ImageKey = keyof typeof IMAGES;

export const VIDEOS = {
  hero: '/media/herovideo.mp4',
  beans: '/media/beans.mp4',
} as const;
