/**
 * Media pipeline — CRÈMA HOUSE
 *
 * Reads the original assets from /media (untouched, source of truth), emits
 * web-optimised WebP into /public/media, copies the videos across, and
 * generates src/lib/media.ts containing intrinsic dimensions + inline blur
 * placeholders so <Image> never causes layout shift and never flashes empty.
 *
 * Run: npm run media
 */
import { readdir, mkdir, readFile, writeFile, copyFile, stat } from 'node:fs/promises';
import { join, extname, basename } from 'node:path';
import sharp from 'sharp';

const SRC = 'media';
const OUT = join('public', 'media');
const MANIFEST = join('src', 'lib', 'media.ts');

/** "Iced Mocha Frappe.png" -> "iced-mocha-frappe" */
const slugify = (file) =>
  basename(file, extname(file))
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();

/** Videos keep hand-picked names so the markup reads intentionally. */
const VIDEO_NAMES = { hero: 'hero', hero1: 'hero1', scroll: 'beans' };

const IMAGE_QUALITY = 88;
const BLUR_WIDTH = 14;

async function buildImage(file) {
  const slug = slugify(file);
  const input = join(SRC, file);
  const output = join(OUT, `${slug}.webp`);

  const pipeline = sharp(input).rotate();
  const { width, height } = await pipeline.metadata();

  await pipeline
    .clone()
    .webp({ quality: IMAGE_QUALITY, effort: 6 })
    .toFile(output);

  // Tiny inline placeholder — blurred, ~400 bytes, shipped in the HTML.
  const blur = await sharp(input)
    .rotate()
    .resize(BLUR_WIDTH, null, { fit: 'inside' })
    .webp({ quality: 45 })
    .toBuffer();

  const before = (await stat(input)).size;
  const after = (await stat(output)).size;
  const saved = (100 - (after / before) * 100).toFixed(0);
  console.log(
    `  ${slug.padEnd(26)} ${width}x${height}  ` +
      `${(before / 1048576).toFixed(1)}MB -> ${(after / 1024).toFixed(0)}KB  (-${saved}%)`
  );

  return {
    slug,
    width,
    height,
    src: `/media/${slug}.webp`,
    blurDataURL: `data:image/webp;base64,${blur.toString('base64')}`,
  };
}


/**
 * Social card, 1200x630.
 *
 * Composed here rather than by next/og: satori has no system fonts and needs
 * a font binary supplied for every render, which would make the production
 * build depend on either a network fetch or a vendored font file. The card
 * is photograph, scrim and rule — the title and description travel with the
 * link as text anyway.
 */
async function buildSocialCard() {
  const OG = { width: 1200, height: 630 };

  const scrim = Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${OG.width}" height="${OG.height}">
      <defs>
        <linearGradient id="g" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stop-color="#0a0705" stop-opacity="0.62"/>
          <stop offset="42%" stop-color="#0a0705" stop-opacity="0.30"/>
          <stop offset="100%" stop-color="#0a0705" stop-opacity="0.95"/>
        </linearGradient>
      </defs>
      <rect width="100%" height="100%" fill="url(#g)"/>
      <rect x="40" y="40" width="${OG.width - 80}" height="${OG.height - 80}"
            fill="none" stroke="#c08a3e" stroke-opacity="0.55" stroke-width="1"/>
    </svg>`
  );

  await sharp(join(SRC, 'cafe.png'))
    .rotate()
    .resize(OG.width, OG.height, { fit: 'cover', position: 'attention' })
    .composite([{ input: scrim, top: 0, left: 0 }])
    .jpeg({ quality: 88, mozjpeg: true })
    .toFile(join(OUT, 'og.jpg'));

  const size = (await stat(join(OUT, 'og.jpg'))).size;
  console.log(`
Social card
  og.jpg                     ${OG.width}x${OG.height}  ${(size / 1024).toFixed(0)}KB`);
}

async function main() {
  await mkdir(OUT, { recursive: true });
  const files = await readdir(SRC);

  console.log('\nImages');
  const images = [];
  for (const file of files.filter((f) => /\.(png|jpe?g)$/i.test(f))) {
    images.push(await buildImage(file));
  }

  console.log('\nVideos');
  const videos = [];
  for (const file of files.filter((f) => /\.mp4$/i.test(f))) {
    const key = slugify(file);
    const name = VIDEO_NAMES[key] ?? key;
    await copyFile(join(SRC, file), join(OUT, `${name}.mp4`));
    const size = (await stat(join(SRC, file))).size;
    console.log(`  ${name.padEnd(26)} ${(size / 1048576).toFixed(1)}MB`);
    videos.push({ name, src: `/media/${name}.mp4` });
  }

  await buildSocialCard();

  images.sort((a, b) => a.slug.localeCompare(b.slug));

  const body = images
    .map(
      (i) =>
        `  '${i.slug}': {\n` +
        `    src: '${i.src}',\n` +
        `    width: ${i.width},\n` +
        `    height: ${i.height},\n` +
        `    blurDataURL:\n      '${i.blurDataURL}',\n` +
        `  },`
    )
    .join('\n');

  const videoBody = videos
    .map((v) => `  ${v.name}: '${v.src}',`)
    .join('\n');

  await writeFile(
    MANIFEST,
    `/* eslint-disable */\n` +
      `// GENERATED by scripts/optimize-media.mjs — do not edit by hand.\n` +
      `// Run \`npm run media\` to regenerate.\n\n` +
      `export type MediaAsset = {\n` +
      `  readonly src: string;\n` +
      `  readonly width: number;\n` +
      `  readonly height: number;\n` +
      `  readonly blurDataURL: string;\n` +
      `};\n\n` +
      `export const IMAGES = {\n${body}\n} as const satisfies Record<string, MediaAsset>;\n\n` +
      `export type ImageKey = keyof typeof IMAGES;\n\n` +
      `export const VIDEOS = {\n${videoBody}\n} as const;\n\n` +
      `export const image = (key: ImageKey): MediaAsset => IMAGES[key];\n`,
    'utf8'
  );

  console.log(`\nWrote ${MANIFEST} (${images.length} images, ${videos.length} videos)\n`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
